OnlineShopping/OnlineShopping/Models/Shopping.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShopping.Models
{
    public class ShippingDetails
    {
        public string OrderId { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        public string State { get; set; }
        [Required]
        public string Country { get; set; }
        [Required]
        public string ZipCode { get; set; }   
        public decimal TotalPrice { get; set; }
        [Required]
        public string PaymentType { get; set; }
    }
}

OnlineShopping/OnlineShopping/Controllers/ShoppingController.cs
using OnlineShopping.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShopping.DAL;
using System.Data.SqlClient;
using System.Data;
using OnlineShopping.Filters;
using OnlineShopping.Models;

namespace OnlineShopping.Controllers
{
    [FrontPageActionFilter]
    [AuthorizeUser]
    public class ShoppingController : Controller
    {
        #region Other Class references ...         
        // Instance on Unit of Work         
        public GenericUnitOfWork _unitOfWork = new GenericUnitOfWork();
        private int _memberId;
        public int memberId
        {
            get { return Convert.ToInt32(Session["MemberId"]); }
            set { _memberId = Convert.ToInt32(Session["MemberId"]); }
        }
        #endregion

        /// <summary>
        /// Add Product To Cart
        /// </summary>
        /// <param name="productId"></param>
        /// <returns></returns>
        public ActionResult AddProductToCart(int productId)
        {
            Tbl_Cart c = new Tbl_Cart();
            c.AddedOn = DateTime.Now;
            c.CartStatusId = 1;
            c.MemberId = memberId;
            c.ProductId = productId;
            c.UpdatedOn = DateTime.Now;
            _unitOfWork.GetRepositoryInstance<Tbl_Cart>().Add(c);
            _unitOfWork.SaveChanges();
            TempData["ProductAddedToCart"] = "Product added to cart successfully";
            return RedirectToAction("Index", "Search");
        }

        /// <summary>
        /// MyCart
        /// </summary>
        /// <returns>List of cart items</returns>
        public ActionResult MyCart()
        {
            List<USP_MemberShoppingCartDetails_Result> cd = _unitOfWork.GetRepositoryInstance<USP_MemberShoppingCartDetails_Result>().GetResultBySqlProcedure("USP_MemberShoppingCartDetails @memberId",
                new SqlParameter("memberId", System.Data.SqlDbType.Int) { Value = memberId }).ToList();
            return View(cd);
        }

        /// <summary>
        /// Remove Cart Item
        /// </summary>
        /// <param name="productId"></param>
        /// <returns></returns>
        public ActionResult RemoveCartItem(int productId)
        {
            Tbl_Cart c = _unitOfWork.GetRepositoryInstance<Tbl_Cart>().GetFirstOrDefaultByParameter(i => i.ProductId == productId && i.MemberId == memberId && i.CartStatusId == 1);
            c.CartStatusId = 2;
            c.UpdatedOn = DateTime.Now;
            _unitOfWork.GetRepositoryInstance<Tbl_Cart>().Update(c);
            _unitOfWork.SaveChanges();
            return RedirectToAction("MyCart");
        }

        /// <summary>
        /// CheckOut the Cart items
        /// </summary>
        /// <returns></returns>
        public ActionResult CheckOut()
        {
            List<USP_MemberShoppingCartDetails_Result> cd = _unitOfWork.GetRepositoryInstance<USP_MemberShoppingCartDetails_Result>().GetResultBySqlProcedure("USP_MemberShoppingCartDetails @memberId",
               new SqlParameter("memberId", System.Data.SqlDbType.Int) { Value = memberId }).ToList();
            ViewBag.TotalPrice = cd.Sum(i => i.Price);
            ViewBag.CartIds = string.Join(",", cd.Select(i => i.CartId).ToList());
            return View(cd);
        }

        /// <summary>
        /// Payment Success
        /// </summary>
        /// <param name="shippingDetails"></param>
        /// <returns></returns>
        public ActionResult PaymentSuccess(ShippingDetails shippingDetails)
        {
            Tbl_ShippingDetails sd = new Tbl_ShippingDetails();
            sd.MemberId = memberId;
            sd.AddressLine = shippingDetails.Address;
            sd.City = shippingDetails.City;
            sd.State = shippingDetails.State;
            sd.Country = shippingDetails.Country;
            sd.ZipCode = shippingDetails.ZipCode;
            sd.OrderId = Guid.NewGuid().ToString();
            sd.AmountPaid = shippingDetails.TotalPrice;
            sd.PaymentType = shippingDetails.PaymentType;
            _unitOfWork.GetRepositoryInstance<Tbl_ShippingDetails>().Add(sd);
            _unitOfWork.GetRepositoryInstance<Tbl_Cart>().UpdateByWhereClause(i => i.MemberId == memberId && i.CartStatusId == 1, (j => j.CartStatusId = 3));
            _unitOfWork.SaveChanges();
            if (!string.IsNullOrEmpty(Request["CartIds"]))
            {
                int[] cartIdsToUpdate = Request["CartIds"].Split(',').Select(Int32.Parse).ToArray();
                _unitOfWork.GetRepositoryInstance<Tbl_Cart>().UpdateByWhereClause(i => cartIdsToUpdate.Contains(i.CartId), (j => j.ShippingDetailId = sd.ShippingDetailId));
                _unitOfWork.SaveChanges();

            }
            return View(sd);
        }
    }
}

OnlineShopping/OnlineShopping/Views/Shopping/CheckOut.cshtml
@model List<OnlineShopping.DAL.USP_MemberShoppingCartDetails_Result>
@{
    ViewBag.Title = "MyCart";
    Layout = "~/Views/Shared/_FrontLayout.cshtml";
}
<style>
    .checkout {
        background-color: forestgreen;
        top: 54px;
        width: 203px;
        right: 86px;
        font-size: 14px;
    }
</style>

<div id="dvFilterSearch" style="margin-top:30px;">
    <div class="mainServices clearfix">
        <div class="container">
            <h2 style="margin:20px;text-align:center;font-weight:bold;">
                Checkout
            </h2>
            <!-- Start servicesRight-->
            <div class="servicesRight1">
                @if (Model.Count() > 0)
                {
                    <div style="background-color: white;  padding: 20px;">
                        <b>You have following @Model.Count() items in your cart</b>
                        <br /><br />
                        @foreach (var item in Model)
                        {
                            <h3><a title="View Product Detail" href="/search/ProductDetail?pId=@item.ProductId"> <b> @item.ProductName</b>,  </a> <span>Price : </span><b>@item.Price</b></h3>
                        }
                    </div>
                }
                else
                {
                    <div class="tabContent" id="tab3">
                        <div class="clearfix">
                            <div class="detailservicesBox clearfix">
                                <div style="background-color: #fff; text-align: center; padding: 40% 0; ">
                                    <h2>No Records found</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                <br />
                <br />
                <h3 style="font-weight: bold;color: brown;"> Total Amount to Pay : @Model.Sum(i => i.Price)</h3>
                @Html.Partial("_ShippingAddress", new OnlineShopping.Models.ShippingDetails())
            </div>
        </div>
    </div>
</div>

OnlineShopping/OnlineShopping/Views/Shopping/MyCart.cshtml
@model List<OnlineShopping.DAL.USP_MemberShoppingCartDetails_Result>
    @{
        ViewBag.Title = "MyCart";
        Layout = "~/Views/Shared/_FrontLayout.cshtml";
    }
    <style>
        .checkout {
            background-color: forestgreen;
            /* float: right; */
            top: 54px;
            width: 203px;
            right: 86px;
            font-size: 14px;
        }
    </style>

    <div id="dvFilterSearch" style="margin-top:30px;">
        <div class="mainServices clearfix">
            <div class="container">

                <h2 style="margin:20px;text-align:center;font-weight:bold;">
                    My Cart Details
                @if (Model.Count() > 0)
                { <a style=" " class="RemoveCartBtn checkout" href="/shopping/checkout">Proceed to Checkout</a>}
                </h2>
                <!-- Start servicesRight-->
                <div class="servicesRight1">
                    @if (Model.Count() > 0)
                    {
                        <!--Start pricelowHigh-->
                        <div class="pricelowHigh clearfix">
                            <!--Start Services Man-->
                            <div class="tabContent" id="tab2">
                                <!--Start Services Man-->
                                <div class="servicesPerson1 clearfix">
                                    @foreach (var item in Model)
                                    {
                                         <!--Start detailServicesBox-->
                                        <div class="detailservicesBox clearfix">
                                            <div class="detailLeft fl">
                                                <div class="DservicesImg1">
                                                    @if (File.Exists(Server.MapPath(System.Configuration.ConfigurationManager.AppSettings["ProductImage"] + "/Small/" + item.ProductId + "_" + item.ProductImage)))
                                                    {
                                                        <img style="height: 90px;" src="@(System.Configuration.ConfigurationManager.AppSettings["ProductImage"]+"/Small/"+item.ProductId+ "_"+item.ProductImage)" alt="img" />
                                                    }
                                                    else
                                                    {
                                                        <img style="height: 90px;" src="@(System.Configuration.ConfigurationManager.AppSettings["ProductImage_Default"])" alt="img" />
                                                    }
                                                </div>
                                            </div>
                                            <div class="detailRight fr">
                                                <div class="innerDetails">
                                                    <h1><a title="View Product Detail" href="/search/ProductDetail?pId=@item.ProductId">@item.ProductName</a></h1>
                                                    <h3>Category <a style="cursor:pointer" title="Click to View the products of this category" href="/search/knowbleprofile?pId=@item.ProductId">@(item.ProductName)</a></h3>
                                                    <p><b>Price : </b><b>@item.Price</b></p>
                                                    <p><a href="/shopping/removecartitem?productId=@item.ProductId" onclick="show_progress();" class="RemoveCartBtn">Remove from cart</a></p>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="tabContent" id="tab3">
                            <div class="clearfix">
                                <div class="detailservicesBox clearfix">
                                    <div style="background-color: #fff; text-align: center; padding: 40% 0; ">
                                        <h2>No Records found</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

OnlineShopping/OnlineShopping/Views/Shopping/PaymentSuccess.cshtml
@model OnlineShopping.DAL.Tbl_ShippingDetails
@{
    ViewBag.Title = "PaymentSuccess";
    Layout = "~/Views/Shared/_FrontLayout.cshtml";
}
<div id="dvFilterSearch" style="margin-top:30px;">
    <div class="mainServices clearfix">
        <div class="container">
            <div style="background-color:white;margin-top:40px;padding:30px">
                <h2 style="margin:20px;text-align:center;font-weight:bold;color:green;">
                    Congratulations!!! Your Order is Placed Successfully
                </h2>
                <div class="servicesRight1">
                    <table>
                        <tr><td><b>Payment Details:</b></td><td>&nbsp;</td></tr>
                        <tr><td>Order Id:</td><td>@Model.OrderId</td></tr>
                        <tr><td>Amount Paid:</td><td>@Model.AmountPaid</td></tr>
                        <tr><td>Payment Type:</td><td>@Model.PaymentType</td></tr>
                        <tr><td><b>&nbsp;</b></td><td>&nbsp;</td></tr>
                        <tr><td><b>Shipping Details:</b></td><td>&nbsp;</td></tr>
                        <tr><td>Address:</td><td>@Model.AddressLine</td></tr>
                        <tr><td>City:</td><td>@Model.City </td></tr>
                        <tr><td>State:</td><td>@Model.State</td></tr>
                        <tr><td>Country:</td><td>@Model.Country</td></tr>
                        <tr><td>Zip Code:</td><td>@Model.ZipCode</td></tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

OnlineShopping/OnlineShopping/Views/Shopping/_ShippingAddress.cshtml
@model OnlineShopping.Models.ShippingDetails

@using (Html.BeginForm("PaymentSuccess", "Shopping"))
{
    <div class="clearfix">
        <div class="container">
            @Html.AntiForgeryToken()
            <input name="TotalPrice" value="@ViewBag.TotalPrice" style="position: absolute;  visibility: hidden;" />
            <input type="hidden" value="@ViewBag.CartIds" name="CartIds" />
            <div class="formRow clearfix" style="margin:20px 0;">
                <b>Select Payment Type*</b>
                <div style="margin-top: 8px;">
                    <label for="radio-2" class="css-label">
                        @Html.RadioButton("PaymentType", "Pay Using Debit/Credit Card", new { @class = "css-checkbox" })
                        Pay Using Debit/Credit Card
                    </label>
                    <label for="radio-2" class="css-label">
                        @Html.RadioButton("PaymentType", "Pay Using Net banking", new { @class = "css-checkbox" })
                        Pay Using Net banking
                    </label>
                    <label for="radio-2" class="css-label">
                        @Html.RadioButton("PaymentType", "Cash On Delivery", new { @class = "css-checkbox" })
                        Cash On Delivery
                    </label>
                    @Html.ValidationMessageFor(m => m.PaymentType)
                </div>
            </div>

            <b>Shipping Address</b>
            <div class="formRow clearfix" style="margin-top: 8px;">
                <label>Address*  @Html.ValidationMessageFor(m => m.Address)</label>
                @Html.TextBoxFor(m => m.Address, new { @class = "inputComn", @placeholder = "Address" })
            </div>

            <div class="formRow clearfix">
                <div class="half fl">
                    <label>City*  @Html.ValidationMessageFor(m => m.City)</label>
                    @Html.TextBoxFor(m => m.City, new { @class = "inputComn", @placeholder = "City" })
                </div>
                <div class="half fr">
                    <label>State*  @Html.ValidationMessageFor(m => m.State)</label>
                    @Html.TextBoxFor(m => m.State, new { @class = "inputComn", @placeholder = "State" })
                </div>
            </div>

            <div class="formRow clearfix">
                <div class="half fl">
                    <label>Country*  @Html.ValidationMessageFor(m => m.Country)</label>
                    @Html.TextBoxFor(m => m.Country, new { @class = "inputComn", @placeholder = "Country" })
                </div>
                <div class="half fr">
                    <label>Zip Code*  @Html.ValidationMessageFor(m => m.ZipCode)</label>
                    @Html.TextBoxFor(m => m.ZipCode, new { @class = "inputComn", @placeholder = "Zip Code" })
                </div>
            </div>
            <input type="submit" class="contactBtn signupBtn" value="Proceed to Pay" />
        </div>
    </div>
}